name: com.gogospider.booking
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 5.12.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common
  nb_utils: ^4.6.20
  google_fonts: ^3.0.1
  html: ^0.15.0
  intl: ^0.17.0
  cached_network_image: ^3.2.2
  url_launcher: ^6.1.5

  # Firebase
  firebase_crashlytics: ^2.8.10
  firebase_core: ^1.24.0
  firebase_auth: ^3.8.0
  firebase_storage: ^10.3.8
  firebase_remote_config: ^2.0.17
  cloud_firestore: ^3.4.7

  # Push Notification

  # State Management
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1

  # Icon
  flutter_vector_icons: ^1.0.0
  flutter_svg: ^1.1.5

  # Image
  image_picker: ^0.8.5+3
  photo_view: ^0.14.0
  lottie: ^1.4.2

  # Other
  country_code_picker: ^2.0.2
  flutter_custom_tabs: ^1.0.4
  permission_handler: ^10.2.1
  paginate_firestore: ^1.0.3+1
  flutter_html: ^3.0.0-alpha.5

  # Social Login
  google_sign_in: ^5.4.1

  # Payment Gateways
  razorpay_flutter: ^1.3.2
  flutterwave_standard: ^1.0.4
  flutter_stripe: ^8.0.0

  # Map
  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.1
  geocoding: ^2.0.5

  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.2.1
  # stripe_payment: ^1.1.4
  flutter_credit_card: ^3.0.4
  sqflite: ^2.2.0+3
  badges: ^2.0.3
  provider: ^6.0.4
  uuid: ^3.0.7
  mask_text_input_formatter: ^2.4.0
  http: ^0.13.5
  day_night_time_picker: ^1.2.0+2
  telephony: ^0.2.0
  otp_text_field: ^1.1.3
  onesignal_flutter: ^3.5.1
  another_stepper: ^1.2.2
  screenshot: ^1.3.0
  flutter_google_places: ^0.3.0

  location: ^5.0.3

  # modal_bottom_sheet: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/CoolDude53/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  firebase_core_platform_interface: 4.5.1
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/lottie/
